// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reserva.Data;

#nullable disable

namespace Reserva.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007143232_addingthefithyRooms")]
    partial class addingthefithyRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Reserva.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<int>("Employeed_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("End Date");

                    b.Property<int>("Guest_id")
                        .HasColumnType("int");

                    b.Property<int>("Room_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Start Date");

                    b.Property<double>("Total_cost")
                        .HasColumnType("double")
                        .HasColumnName("Total Cost");

                    b.HasKey("Id");

                    b.HasIndex("Employeed_id");

                    b.HasIndex("Guest_id");

                    b.HasIndex("Room_id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Reserva.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("Firt_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Firt Name");

                    b.Property<string>("Identification_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Identification Number");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Last Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Reserva.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("Firts_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("First Name");

                    b.Property<string>("Identification_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Identification Number");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Last Name");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Phone Number");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Reserva.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Availability");

                    b.Property<byte>("Max_ocuppancy_persons")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("Max Ocupancy");

                    b.Property<double>("Price_per_night")
                        .HasColumnType("double")
                        .HasColumnName("Price Per Night");

                    b.Property<int>("Room_number")
                        .HasColumnType("int")
                        .HasColumnName("Room Number");

                    b.Property<int>("Room_type_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Room_type_id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 1,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 2,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 3,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 4,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 5,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 6,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 7,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 8,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 9,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 10,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 11,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 12,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 12,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 13,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 13,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 14,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 14,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 15,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 15,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 16,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 16,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 17,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 17,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 18,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 18,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 19,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 19,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 20,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 20,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 21,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 21,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 22,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 22,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 23,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 23,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 24,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 24,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 25,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 25,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 26,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 26,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 27,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 27,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 28,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 28,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 29,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 29,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 30,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 30,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 31,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 31,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 32,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 32,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 33,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 33,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 34,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 34,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 35,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 35,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 36,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 36,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 37,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 37,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 38,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 38,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 39,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)4,
                            Price_per_night = 200.0,
                            Room_number = 39,
                            Room_type_id = 4
                        },
                        new
                        {
                            Id = 40,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 40,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 41,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 41,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 42,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 42,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 43,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 43,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 44,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 44,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 45,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 45,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 46,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 46,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 47,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)1,
                            Price_per_night = 50.0,
                            Room_number = 47,
                            Room_type_id = 1
                        },
                        new
                        {
                            Id = 48,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 48,
                            Room_type_id = 2
                        },
                        new
                        {
                            Id = 49,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 150.0,
                            Room_number = 49,
                            Room_type_id = 3
                        },
                        new
                        {
                            Id = 50,
                            Availability = true,
                            Max_ocuppancy_persons = (byte)2,
                            Price_per_night = 80.0,
                            Room_number = 50,
                            Room_type_id = 2
                        });
                });

            modelBuilder.Entity("Reserva.Models.Room_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Room Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = " Una acogedora habitación básica con una cama individual, ideal para viajeros solos. ",
                            Name = "Habitación Simple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ofrece flexibilidad con dos camas individuales o una cama doble, perfecta para parejas o amigos. ",
                            Name = "Habitacion Doble"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espaciosa y lujosa, con una cama king size y una sala de estar eparada, ideal para quienes buscan confort y exclusividad.",
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Description = " Diseñada para familias, con espacio adicional y varias camas para una estancia cómoda.",
                            Name = "Habitacion Familiar"
                        });
                });

            modelBuilder.Entity("Reserva.Models.Booking", b =>
                {
                    b.HasOne("Reserva.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Employeed_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserva.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("Guest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserva.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("Room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Reserva.Models.Room", b =>
                {
                    b.HasOne("Reserva.Models.Room_type", "Room_Type")
                        .WithMany()
                        .HasForeignKey("Room_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room_Type");
                });
#pragma warning restore 612, 618
        }
    }
}
